### ISSUE TITLE
Registrierung-Issue

### ISSUE THREAD

**Issue by kjoscha** [kjoscha/bastabiet#21]
@andneuma  kannst du dir das etwas drunter vorstellen?

> Ich habe aber leider seit gestern Probleme und krieg das nicht hin, zu bieten. Ich habe mich (für unseren EA) registriert, "Bastabiet-Account aktivieren"-Mail bekommen, aber wenn ich dem Link folge, heißt es "Aktivierungs-Link ungültig!". Neu registrieren geht nicht, weil das checkt, dass ich schon registriert bin. Ideen, was ich tun kann? Sonst könnte sich noch eine andere Person aus dem EA registrieren, falls das dann nicht zu verwirrenden Dopplungen führt... Daher wollte ich erstmal nachfragen.

**Comment by kjoscha** [comment]
+1

**Comment by kjoscha** [comment]
es ging bei ihnen nun, nachdem ich den accout gelöscht habe und sie sich neu registriert haben.

können wir implementieren, dass wir bei erfolglosem aktivieren eine Mail bekommen?!

**Comment by andneuma** [comment]
Klar, kein Problem. Frage ist, warum der Link für sie ungültig war...
war das bei allen EA so?
